version: "3.8"
networks:
  app-network:

services:
  # setup aps
  clean-architecture-clone:
    container_name: clean_architecture_clone
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "no"
    ports:
      - 3000:3000
    volumes:
      - "./src:/usr/app/src"
      - "./tests:/usr/app/test"
      - "/usr/app/node_modules"
    environment:
      - MONGO_URL=mongodb://mongo-server/cleandb
      - PRIVATE_KEY_PASSPHRASE=clean-pass
      - IN_CONTAINER=true
    networks:
      - app-network
    depends_on:
      - mongo-server
  # setup mongo
  mongo-server:
    image: mongo
    container_name: mongo-server
    restart: "no"
    ports:
      - 27017
    volumes:
      - "./docker/mongodb:/data/db"
    networks:
      - app-network
  # setup redis
  redis-server:
    image: redis
    restart: "no"
    ports:
      - 6379
    command: redis-server --save
    networks:
      - app-network
